//weapon todo list

//test BFG Altfire 
//go back and smoothen parts of gun anims with a_weaponoffset and WOF_INTERPOLATE
//adjust chaingun sounds (particularly reloading sounds)

class DeimosWeapon : Weapon
{
	Default
	{
		Weapon.Bobstyle "Alpha";
		Weapon.BobRangeX 0.4;
		Weapon.BobRangeY 0.4;
		Weapon.BobSpeed 2.5;
		
		+WEAPON.NOAUTOFIRE;
		+WEAPON.NOALERT;
		+WEAPON.AMMO_OPTIONAL;
	}
	
	States
	{
		Movement:
			#### A 1;
			#### A 0 A_SetCrosshair(98);
			#### A 0 A_JumpIf(getplayerinput(input_sidemove), "Evade");
			#### A 0 A_JumpIf(getplayerinput(input_buttons) & bt_back , "Evade");
		SprintStartup: //actual sprint startup
			#### A 0 A_SetSpeed(1.35);
			#### A 1 A_WeaponOffset(0,40,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,42,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,46,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,48,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,50,WOF_INTERPOLATE);
		SprintLoop:
			#### A 1;
			//[pop] Sanitize this for universal use
			//#### A 0 A_JumpIf(getplayerinput(input_buttons) & bt_attack, "SprintPunch"); //A_Refire("SprintPunch")
			#### A 0 A_JumpIf(getplayerinput(input_buttons) & bt_zoom, "SprintJump");
			#### A 0 A_JumpIf(invoker.getcrouchfactor() < 1.0, "Slide");
			#### A 0 A_JumpIf(getplayerinput(input_buttons) & bt_forward, "SprintLoop");
		SprintOut:
			#### A 1 A_WeaponOffset(0,48,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			#### A 0 A_SetSpeed(0.9);
			#### A 0 A_Jump(256, "Ready");
			Goto Ready;
		SprintJump: 
			#### A 0;
			#### A 0 A_JumpIfInventory("SprintJumpCooldown",1,"FatiguedSprintJump");
			#### A 0 A_CheckFloor(1);
			Goto SprintLoop;
			#### A 1;
			#### A 0 A_GiveInventory("SprintJumpFatigue",1);
			#### A 0 A_ChangeVelocity(12,0,8,CVF_RELATIVE);
			// #### A 0 A_Recoil(-10);
			Goto SprintLoop	;
		FatiguedSprintJump: 
			#### A 0;
			#### A 0 A_CheckFloor(1);
			Goto SprintLoop;
			#### A 1;
			#### A 0 A_Recoil(-1);
			Goto SprintLoop;
		Slide: 
			#### A 0;
			#### A 0 A_CheckFloor(1);
			Goto SprintLoop;
			#### A 0 A_PlaySound("misc/slide");
			#### A 0 A_JumpIfInventory("SlideCooldown",1,"FatiguedSlide");
			#### A 0 A_GiveInventory("SlideFatigue",1);
			#### A 0 A_SetSpeed(10);
			#### A 1 A_WeaponOffset(0,40,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,38,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,36,WOF_INTERPOLATE);
			#### A 0 A_SetSpeed(5);
			#### A 1 A_WeaponOffset(0,34,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
			#### A 0 A_Jump(256, "Ready");
			Goto Ready;
		FatiguedSlide: 
			#### A 0;
			#### A 0 A_CheckFloor(1);
			Goto SprintLoop;
			#### A 0 A_PlaySound("misc/slidefatigued");
			#### A 0 A_SetSpeed(3);
			#### A 1 A_WeaponOffset(0,40,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,38,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,36,WOF_INTERPOLATE);
			#### A 0 A_SetSpeed(2);
			#### A 1 A_WeaponOffset(0,34,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
			#### A 0 A_Jump(256, "Ready");
			Goto Ready;
		Evade: 
			#### A 1 A_WeaponOffset(0,40);
			#### A 0 A_JumpIfInventory("DodgeCooldown",1,"FatiguedEvade");
			#### A 0 A_GiveInventory("DodgeFatigue",1);
			#### A 0 A_PlaySound("misc/dodge");
			#### A 0 A_SetSpeed(8);
			#### A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,48,WOF_INTERPOLATE);
			#### A 0 A_SetSpeed(0.5);
			#### A 1 A_WeaponOffset(0,50,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,56,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,54,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,53,WOF_INTERPOLATE);
			//#### A 2 A_WeaponOffset(0,53,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,50,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,48,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,47,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,46,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,45,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,43,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,42,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,41,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,40,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,38,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,37,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,36,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,34,WOF_INTERPOLATE);
			#### A 0 A_Jump(256, "Ready");
			Goto Ready;
		FatiguedEvade: 
			#### A 1 A_WeaponOffset(0,40,WOF_INTERPOLATE);
			#### A 0 A_PlaySound("misc/dodgefatigued");
			#### A 0 A_SetSpeed(6);
			#### A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,48,WOF_INTERPOLATE);
			#### A 0 A_SetSpeed(0.2) ;
			#### A 1 A_WeaponOffset(0,50,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,56,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,54,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,53,WOF_INTERPOLATE);
			#### A 8 A_WeaponOffset(0,53,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,50,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,48,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,47,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,46,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,45,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			//#### A 1 A_WeaponOffset(0,43,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,42,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,41,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,40,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,39,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,38,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,37,WOF_INTERPOLATE);
			#### A 0 A_SetSpeed(0.5);
			#### A 1 A_WeaponOffset(0,36,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
			#### A 1 A_WeaponOffset(0,34,WOF_INTERPOLATE);
			#### A 0 A_Jump(256, "Ready");
			Goto Ready;
	}
}